version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv #optional
      - ENCRYPTION #optional
    environment:
      ENCRYPTION: example #optional
    ports:
      - "8090:8090"
    volumes:
      - ./docker-compose/pocketbase/data:/pb_data
      - ./docker-compose/pocketbase/public:/pb_public #optional
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    build:
      context: .
      dockerfile: ./docker-compose/nginx/Dockerfile
    ports:
      - 8765:80
    volumes:
      - ./php:/var/www/html
    depends_on:
      - php
  php:
    build: 
      context: .
      dockerfile: ./docker-compose/php/Dockerfile
    volumes:
      - ./php:/var/www/html
  reactui:
    stdin_open: true
    build:
      dockerfile: ../docker-compose/react/Dockerfile
      context: ./reactui
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./reactui:/app